### ISSUE TITLE
No meeting planned!

### ISSUE THREAD

**Issue by simi** [zizkovrb/pivo#1]
There's a serious bug in all @zizkovrb projects! I found it recently. No beer meeting is planned.

@pepe, @pajasevi can you help me to resolve this one? It is **critical**!

**Comment by simi** [comment]
Maybe @papricek can contribute to this also.

**Comment by pajasevi** [comment]
I think we should schedule a meeting on this one, because it might be tough one to resolve.

**Comment by papricek** [comment]
hmm guys thats serious. Although not a member, I can bring some experience with drinking shots and liquors to solve this properly.

**Comment by simi** [comment]
_INFO:_ I'm writting message to http://www.openwall.com/lists/oss-security/ to assign CVE for this critical issue.

**Comment by pepe** [comment]
Sorry guys, drunk beer yday a little.

I am sure we have make https://github.com/moment/moment/ for that beer. What about next wed?

And who will provide testbed for me?

**Comment by simi** [comment]
I think @pajasevi can contribute with testbed since @papricek filled his free places with fresh washing machines.

**Comment by pepe** [comment]
So what could be the term? And also I will make it the foundational meeting. So it should be on the fullmoon (next is 10/8 on wed). And only suitable place is illegal pub (yes Josef that one).

**Comment by papricek** [comment]
I'll take a cock to sacrifice in honour of žrb. 
![download](https://cloud.githubusercontent.com/assets/33353/4438265/e83f4476-47a9-11e4-8845-c27f003e5f15.jpeg)

**Comment by pepe** [comment]
Well I take my cock everywhere. And no sacrifices with it
