### ISSUE TITLE
Meeting zwei!

### ISSUE THREAD

**Issue by simi** [zizkovrb/pivo#2]
Das @zizkovrb/owners Bier zwei!

Wann werden wir uns zu treffen?

Kleine Speicher von ŽRBConf 2014:

![zrbconf2014](https://cloud.githubusercontent.com/assets/193936/5678980/b090dc48-97f8-11e4-8e1b-d3b27e967ee8.png)

@pepe @pajasevi @papricek

**Comment by pepe** [comment]
Actually January is the dry month for me, so I am avoiding the pub as hard as I can. 

But in February, I am crazy in love with beer!

**Comment by papricek** [comment]
Pivo jako jo

2015-01-09 12:45 GMT+01:00 Josef Pospíšil notifications@github.com:

**Comment by simi** [comment]
@pepe Entschuldigen sie mich bitte Ich vergaß. Februar ist auch akzeptabel.

@papricek :de: :gb: ?

**Comment by papricek** [comment]
@simi :us:

**Comment by simi** [comment]
:euro: :european_castle: :european_post_office:

**Comment by simi** [comment]
@pepe I think you're parched enough now.

@zizkovrb/owners so what's the plan? :flower_playing_cards:

**Comment by pajasevi** [comment]
:beers:

**Comment by papricek** [comment]
:golf:

**Comment by simi** [comment]
@papricek Was?

**Comment by papricek** [comment]
:golf: = optimistich picture

**Comment by simi** [comment]
das optimistich Bild?

**Comment by papricek** [comment]
ein optimistich Bild, mein liebe Pepíček

**Comment by pepe** [comment]
Tak kdy se vám to bude hodit?

**Comment by simi** [comment]
No záleží kdy budeš v Praze.

**Comment by pepe** [comment]
no hele v úterý jdu na nějakej koncík v Roxy, takže příští týden asi ne, ale ten potom bychom mohli ve středu?

**Comment by pajasevi** [comment]
:+1:

**Comment by simi** [comment]
:question: any news?

**Comment by simi** [comment]
@pepe dry month has ended again.
